-- ============================================================
-- Rooms table for SyncWatch lobby
-- Uses the same short text IDs generated by generateRoomId()
-- No auth required — all operations are open
-- ============================================================

CREATE TABLE IF NOT EXISTS public.rooms (
  id            TEXT        NOT NULL PRIMARY KEY,
  host_nickname TEXT        NOT NULL DEFAULT 'Unknown',
  host_avatar   TEXT,
  member_count  INT         NOT NULL DEFAULT 1,
  status        TEXT        NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active', 'inactive')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for listing active rooms sorted by creation time
CREATE INDEX IF NOT EXISTS idx_rooms_status_created
  ON public.rooms (status, created_at DESC);

-- Auto-update updated_at on any row change
CREATE OR REPLACE FUNCTION update_rooms_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER rooms_updated_at
  BEFORE UPDATE ON public.rooms
  FOR EACH ROW EXECUTE FUNCTION update_rooms_updated_at();

-- Row Level Security — open to all (no authentication required)
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rooms_select" ON public.rooms FOR SELECT USING (true);
CREATE POLICY "rooms_insert" ON public.rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "rooms_update" ON public.rooms FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "rooms_delete" ON public.rooms FOR DELETE USING (true);

-- Enable Realtime replication for this table
ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
